import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>See The World!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="font-bold text-slate-800 text-xl text-center p-2">Test</h1>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
